## YAML Template.
name: Messenger
main: com.mahn42.bart4223.messenger.Messenger
version: 0.7
depend: [MAHN42-Framework]
commands:
   messenger_send:
      description: Send Message to offline Player
      usage: /messenger_send
   messenger_recall:
      description: Recall Message to offline Player
      usage: /messenger_recall      
   messenger_listgroups:
      description: List messenger groups 
      usage: /messenger_listgroups 
   messenger_listgroupusers:
      description: List messenger group users 
      usage: /messenger_listgroupusers 